### ISSUE TITLE
support for aws-sdk-js 2.2.0 

### ISSUE THREAD

**Issue by bradoyler** [databank/aws-dynamodb#10]
any plans to create wrapper for `DynamoDB.DocumentClient`?

**Comment by databank** [comment]
Hi Brad,

It looks to me that DocumentClient is a wrapper around AWS.DynamoDB
delegating all its methods to the main library

much like an AWS.DynamoDB + dynamodb-doc

I'm not sure about the pros and cons of wrapping DocumentClient instead

if you have any thoughts please let me know

Thanks

**Comment by bradoyler** [comment]
I see now, thanks for the info. 
This already supports aws-sdk v2.2.x. :dizzy_face:
