### ISSUE TITLE
Consider doco comment for insert_or_update return data variable

### ISSUE THREAD

**Issue by hutch120** [databank/aws-dynamodb#11]
Firstly, well done, nice module.

This is not really an issue, just a doco comment that you might consider adding to save someone a bit of time that is new to AWS DynamoDB (maybe why they are using your module).

Basically I was trying to use a value in the data object returned from insert_or_update to do another operation and it took me a while to figure out that the insert_or_replace returned the old changed data!

After reading the AWS doco section on return values I finally understood that DynamoDB returns the old values if attributes change.

http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html
ALL_OLD - If PutItem overwrote an attribute name-value pair, then the content of the old item is returned.

Anyway, I was thinking a comment, perhaps against the console.log message saying something along the lines of, the data object contains the old data if attributes change.

E.g.
```
DynamoDB
	.table('users')
	...
	.insert_or_update({
	...
	}, function( err, data ) {
		console.log( err, data ); // data object contains the old data if attributes change.
	})
```

Again, cheers for the module.

**Comment by databank** [comment]
Hi and thanks for the feedback, it's good to know when somebody finds this useful

there is return(returnValues) method that that can be used with insert_or_update() 

possible returnValues are : 'NONE', 'ALL_OLD', 'UPDATED_OLD', 'ALL_NEW' and 'UPDATED_NEW'

I will add more comments into the documentation

if you have other suggestions for the doc there is the gh-pages branch waiting merges :)
