### ISSUE TITLE
This is not as much an issue as it is a question

### ISSUE THREAD

**Issue by CreativelyMe** [databank/aws-dynamodb#12]
Your code looks great.  

I'm not sure if you've seen the AWS API Gateway, Lambda implementations, using DynamoDB and node.js.

The way they're doing the update process is painful.  My sense is they could use some of your insight.  

Can I add your library to Lambda?  

Let me know.

Thanks

Joe (Creatively.Me)

**Comment by databank** [comment]
Hey Joe

Yes sure, feel free to use the library however you like!


I"m a happy lambda user myself with 1M+ executions daily, static website on s3, served by cloudfront and dynamic part running trough api gateway connected to lambda

To me, ec2 is the past :) lambda was the missing 
Piece in the puzzle

Thanks for stopping by
