### ISSUE TITLE
Query filtering - support set - contains(), not_contains(), in()

### ISSUE THREAD

**Issue by Looltech** [databank/aws-dynamodb#19]
Do your lib support these functions for set ?

For example: How to pass params to function for these ? I tried to use DynamoDB.SS(['a', 'b']) but get Exception:

`[ValidationException: One or more parameter values were invalid: Invalid number of argument(s) for the IN ComparisonOperator]`

**Comment by databank** [comment]
Hi, 

the lib does not support it, not even sure how aws supports it either.

I will have a look at it and get back to you

Thanks for reminding me

**Comment by neil-rubens** [comment]
AWS supports it with `CONTAINS` or `NOT_CONTAINS`: http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Condition.html

**Comment by databank** [comment]
Hi,

0.1.52 now supports CONTAINS and IN
.having("string").contains("substring")
.having("string_set").contains("a")
.having('object.array[2]').in([3,4,'a'])

all conditions are ANDed together
so SS contains "a" AND "b" resolves to
.having("SS").contains("a").having("SS").contains("b")
