### ISSUE TITLE
ReturnConsumedCapacity How?

### ISSUE THREAD

**Issue by teebu** [databank/aws-dynamodb#20]
How does this work? I couldn't find an example how to get the consumed capacity to return.

**Comment by databank** [comment]
please try this.ConsumedCapacity inside the callback
```
DynamoDB
     .table(tableName)
     .where('partitionKey').eq(partitionValue)
     .where('sortKey').begins_with(sortValue)
     .query(function(err,data) {
          console.log(err,data, this.ConsumedCapacity )
     })
```

**Comment by teebu** [comment]
Im getting null value.

**Comment by databank** [comment]
I see, I'll have a look at it today and get back to you

**Comment by databank** [comment]
Hi,

I've published 0.1.51 which defaults to 'TOTAL' for ReturnConsumedCapacity
you can override with return_consumed_capacity('NONE') // 'NONE'  'INDEXES' 'TOTAL'

Also added it to documentation

Please re-open the issue if you're still getting null

Thanks

**Comment by adrianpraja** [comment]
Hi teebu,

there was a recent but resetting ConsumedCapacity after each call,

I've published 0.1.66 that has it fixed

Thanks.

**Comment by teebu** [comment]
Yes that fixed it.

**Comment by teebu** [comment]
How do you get consumed capacity when using async?

```
async function getItem(table, key, value, callback) {
  return DynamoDB
    .table(table)
    .return_consumed_capacity('INDEXES') // 'TOTAL' | 'INDEXES' | NONE
    .where(key).eq(value)
    .get()
}
```

```
const res = await getItem(table, 'id', 'ulid_2')
console.log(res) // only contains the returned data
```

**Comment by adrianpraja** [comment]
Heyy, 

I dont have a solution for return_consumed_capacity() when using async

If you have any ideas please let me know

**Comment by teebu** [comment]
No good ideas. Maybe add a method to the returned item so it doesn't actually change the returned object's data?

**Comment by adrianpraja** [comment]
yes, that could be a solution, something like .return_raw_result(true)
