### ISSUE TITLE
Region setting problem

### ISSUE THREAD

**Issue by teebu** [databank/aws-dynamodb#21]

**Comment by teebu** [comment]
Trying to do npm test, getting error 'Uncaught ConfigError: Missing region in config' but it is set in the credentials file.

**Comment by databank** [comment]
Hi, Teebu,

Just a quick thought, can you try config as:
{
	credentials: {
		"accessKeyId": "xxxxxx",
		"secretAccessKey": "xxxxxxx",
	},
	"region": "us-east-1",
}

**Comment by teebu** [comment]
I dont use creds in my actual code. But some how the region variable gets erased somewhere inside aws-sdk functions.

**Comment by teebu** [comment]
very strange stuff, i reinstalled the modules, and updated the aws-sdk and aws-dynamodb modules, seems to be working now. i guess you can close this, but i wonder if anyone else experienced this.
